import Head from 'next/head';
// import Image from 'next/image';
import styles from '../styles/Home.module.css';
import DisplayValues from '../components/DisplayValues';
import React from 'react';

export default function Home({ value }) {
  return (
    <React.Fragment>
      <div>
        <Head>
          <title>Hello</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        {value.plot}
      </div>
      <DisplayValues>{value.fullplot}</DisplayValues>
    </React.Fragment>
  );
}

Home.getInitialProps = async () => {
  const res = await fetch('http://localhost:3000/api/hello');
  const json = await res.json();
  return {
    value: json,
  };
};
