import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { connect_to_mongo } from './api/hello';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hello</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </div>
  );
}

export function getServerSideProps() {
  return connect_to_mongo();
}
